version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: genkou-server
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    volumes:
      - ./app/:/usr/src/app/