version: '3.8'

services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    container_name: genkou-api
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    volumes:
      - ./api/app/:/usr/src/app/
    environment:
      - TZ=Asia/Tokyo
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15.6
    container_name: genkou-db
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - "5432:5432"
    volumes:
      - data-vol:/var/lib/postgresql/data
      # - ./db/script/:/docker-entrypoint-initdb.d/
      - ./db/config/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./db/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} || exit 1"]
      interval: 2s
      timeout: 5s
      retries: 5
  mongodb:
    image: mongo:7.0.15
    container_name: genkou-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-store:/data/db
      - ./mongodb/configdb:/data/configdb
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./mongodb/.env

volumes:
  data-vol:
  mongodb-store: